### ISSUE TITLE
For what this dependence "sr_feuser_register"?

### ISSUE THREAD

**Issue by typo3ua** [friendsofmittwald/typo3_forum#274]
How to be, if I not use the `ext: sr_feuser_register`?
If I use another extension for registration users I can not use `ext: typo3 forum`...?

**Comment by sgrossberndt** [comment]
You can use any extension for registering users. You just have to make sure created `fe_users` (and according `fe_groups`) will have their `tx_extbase_type` set to `Mittwald\Typo3Forum\Domain\Model\User\FrontendUser`.

**Comment by typo3ua** [comment]
it is great news, thanks
