### ISSUE TITLE
"topicCount" and "postCount" don't update after deleting topics

### ISSUE THREAD

**Issue by moran284** [friendsofmittwald/typo3_forum#334]
Hello,

when I delete topics or posts the counts in the overview of my sub forums don't update. I deleted every topic and wanted to reset the counts. 

Clearing alle types of cache didn't help.

Thanks a lot,
Julian

**Comment by sgrossberndt** [comment]
The only current possibility to reset the counters is to execute the according cronjob `Count-Checker (typo3_forum)` in scheduler.

**Comment by moran284** [comment]
Hello,

thank your very much for your respond! I created a task in scheduler, but nothing happens:

<img width="1208" alt="Bildschirmfoto 2019-10-05 um 20 29 42" src="https://user-images.githubusercontent.com/55764819/66259239-e5f6e700-e7ae-11e9-85cc-9039c57fc90f.png">

This is my current setup. I have chosen the PID of the sub forum, but also with the PID of the main forum nothing happens.

Sorry if this questions doesn't fit here, but I didn't find something in the manuals.

Bests,
Julian

**Comment by sgrossberndt** [comment]
Ah, the patch to update the counters of forums was added only recently by myself (before that task only updated the counters of users and topics), it is not integrated in a release yet: https://github.com/friendsofmittwald/typo3_forum/commit/b8534ceb5e07048837187d42c3d30df71335e78c
So if you want to use it you have to use `master` of this extension from github and cannot use a released v1.2.0. But maybe @kpurrmann could tag a release? :-)

**Comment by moran284** [comment]
Thanks a lot!
