### ISSUE TITLE
"Sorry, the requested view was not found." and "Unexpected end of JSON input at Function.parse …"

### ISSUE THREAD

**Issue by moran284** [friendsofmittwald/typo3_forum#337]
Hi everyone,

I don't know if this is an issue or if I maybe have made some misconfiguration but at the view to create a topic I geht this error:

> Uncaught SyntaxError: Unexpected end of JSON input
>     at Function.parse [as parseJSON] (<anonymous>)
>     at Object.success (forum.js?1572105821:124)
>     at c (jquery.js:2)
>     at Object.fireWith [as resolveWith] (jquery.js:2)
>     at l (jquery.js:2)
>     at XMLHttpRequest.<anonymous> (jquery.js:2)

And when I click on "Create New Topic" this error displays:

> Sorry, the requested view was not found.
> 
> The technical reason is: No template was found. View could not be resolved for action "create" in class "Mittwald\Typo3Forum\Controller\TopicController".

I reinstalled also the whole extension but with no change.

Thanks for your help and sorry if this doesn't belong here.

Bests,
Julian

**Comment by sgrossberndt** [comment]
Did you find the issue?

**Comment by moran284** [comment]
Hi,

I just worked with an outdated template.
